import uuid
import uuid6
from datetime import datetime, UTC
from pathlib import Path

from celery import shared_task
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from pptx import Presentation
from pptx.util import Inches

from backend.common.storage import minio_client
from backend.common.storage.minio_client import upload_file
from backend.common.schemas.worker_outputs import ReportWorkerOutputs
from backend.common.schemas.worker_envelope import WorkerEnvelope, WorkerSource
from backend.common.schemas.canonical_result import CanonicalResult


# pdf generation
def generate_pdf(report_path: Path, result: CanonicalResult):
    
    c = canvas.Canvas(
        str(report_path),
        pagesize=letter
    )
    y = 750
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, f"Evidence Report: {result.molecule}")
    y -= 40
    c.setFont("Helvetica", 12)

    # summary
    c.drawString(50, y, "Summary: ")
    y -= 20
    text_obj = c.beginText(50, y)
    for line in result.trial_summary.split("\n"):
        text_obj.textLine(line)
    c.drawText(text_obj)
    y = text_obj.getY() - 20

    # key findings
    c.drawString(50, y, "Key Findings:")
    y -= 20
    text_obj = c.beginText(50, y)
    for k in result.key_findings:
        text_obj.textLine(f"• {k}")
    c.drawText(text_obj)
    y = text_obj.getY() - 20

    # follow-up
    c.drawString(50, y, "Suggested Follow-Up:")
    y -= 20
    text_obj = c.beginText(50, y)
    for s in result.suggested_follow_up:
        text_obj.textLine(f"• {s}")
    c.drawText(text_obj)
    y = text_obj.getY() - 20

    # scores
    c.drawString(50, y, f"Data Completeness Score: {result.data_completeness_score}")
    y -= 20
    c.drawString(50, y, f"Confidence Overall: {result.confidence_overall}")

    c.showPage()
    c.save() 

# ppt generation
def generate_ppt(ppt_path: Path, result: CanonicalResult):

    prs= Presentation()

    # Slide 1: Title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = f"Evidence Summary: {result.molecule}"
    subtitle.text = "Generated by Pharma-Agent"

    # Slide 2: Overview
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    body = slide.shapes.placeholders[1].text_frame
    body.text = "Overview"
    body.add_paragraph().text = f"Molecule: {result.molecule}"
    body.add_paragraph().text = f"Data Completeness Score: {result.data_completeness_score}"
    body.add_paragraph().text = f"Confidence Overall: {result.confidence_overall}"

    # Slide 3: Trial Summary
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    body = slide.shapes.placeholders[1].text_frame
    body.text = "Clinical Trial Summary"
    for line in result.trial_summary.split("\n"):
        body.add_paragraph().text = line

    # Slide 4: Key Findings
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    body = slide.shapes.placeholders[1].text_frame
    body.text = "Key Findings"
    for k in result.key_findings:
        body.add_paragraph().text = f"• {k}"

    # Slide 5: Recommendations
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    body = slide.shapes.placeholders[1].text_frame
    body.text = "Suggested Follow-Up"
    for s in result.suggested_follow_up:
        body.add_paragraph().text = f"• {s}"

    prs.save(str(ppt_path))

# celery worker
@shared_task(name="workers.report.worker.run")
def run_report_worker(job_id: str, task_id: str, params: dict):
    # generate pdf and ppt using CanonicalResult 
    # upload artifacts to minio and 
    # return WorkerEnvelope with artifact metadata

    job_uuid = uuid.UUID(job_id)
    task_uuid = uuid.UUID(task_id)

    # 1. load CanonicalResult
    result = CanonicalResult.model_validate(params["canonical_result"])

    # 2. generate files locally
    pdf_name = f"{job_id}_report.pdf"
    ppt_name = f"{job_id}_slides.pptx"

    pdf_path = Path(f"/tmp/{pdf_name}")
    ppt_path = Path(f"/tmp/{ppt_name}")

    generate_pdf(pdf_path, result)
    generate_ppt(ppt_path, result)

    # 3. upload to minio
    pdf_upload = upload_file(
        bucket="artifacts",
        object_name=f"{job_id}_report.pdf",
        file_path=str(pdf_path)
    )
    ppt_upload = upload_file(
        bucket="artifacts",
        object_name=f"{job_id}_slides.pptx",
        file_path=str(ppt_path)
    )

    # 4. worker output schema
    outputs = ReportWorkerOutputs(
        pdf_uri=pdf_upload["uri"],
        ppt_uri=ppt_upload["uri"]
    )

    # 5. return workerenvelope
    envelope = WorkerEnvelope(
        job_id= job_uuid,
        task_id= task_uuid,
        worker="report",
        status="ok",
        confidence=1.0,
        timestamp=datetime.now(UTC),
        outputs=outputs.model_dump(),
        sources=[
            WorkerSource(
                type="generated",
                title="Report Worker Generated Files",
                uri= "minio://artifacts/",
                retrieved_at=datetime.now(UTC)
            )
        ],
        notes=None
    )

    return envelope.model_dump()